### ISSUE TITLE
Letters suddenly mirrored

### ISSUE THREAD

**Issue by Flozn** [rashevskyv/dbi#205] opened 2023-04-01 00:43 UTC
![2023040102365200](https://user-images.githubusercontent.com/52738543/229256856-d59ebe37-3a94-4395-92c8-0c711078c11f.jpg)

OMG you got me, it's April Fool's Day ... nice one. 😋

**Comment by chronoss09** [comment] 2023-04-01 01:10
Same to me since version 519 i think...

**Comment by xxtensazenxx** [comment] 2023-04-01 04:46
Wait is it april fools or is it actually broken....? Also how do we fix it?

**Comment by jixiangqd** [comment] 2023-04-01 04:54
> same issue - so is it april fools or is it actually broken....? Also how do we fix it? I just got a new 1TB SD card and im trying to install games

modify system time to 4/2, seems back to normal.

**Comment by LiloBzH** [comment] 2023-04-01 11:31
April Fool's Day probably :)

**Comment by tuftsanti** [comment] 2023-04-01 14:00
Sorry this is beyond annoying.

**Comment by mirivedan** [comment] 2023-04-01 15:00
No Good Baby

**Comment by Masamune3210** [comment] 2023-04-01 16:18
Well it's a good thing it only lasts for one day and is a completely harmless joke then, huh

**Comment by dkgitdev** [comment] 2023-04-01 16:42
Thanks for clarifying that, reinstalled kefir :D

**Comment by Hagen87** [comment] 2023-04-02 00:59
jajajaja la instale como 15 veces jajajajajajaajajaj

**Comment by saitohhajimi** [comment] 2023-04-02 03:02
During this issue, try restarting or shutting down the console. The console will start lagging.

**Comment by Masamune3210** [comment] 2023-04-02 14:38
Has nothing to do with this, that is caused by you not closing DBI correctly before trying to shut down or restart and is caused by the clock twiddling it does to get faster speeds/use less battery life. Close it before trying to do anything else and it wont happen.

**Closed** 2023-04-06 08:17 UTC
