### ISSUE TITLE
DBI 357 slow in windows explorer, MTP mode

### ISSUE THREAD

**Issue by lowburger** [rashevskyv/dbi#87] opened 2022-02-02 19:31 UTC
Hi, I have report for DBI version 357, I find that files become slow to appear when browse with windows explorer in MTP mode.

For example DBI 350 check retroarch folder with hundreds of files and all appears instantly, in DBI 357 files appear slowly and takes time to load.

Thx for this great app

**Comment by BlackRabbit22** [comment] 2022-02-02 20:43
I can confirm this. 
DBI 350 is much faster than DBI 357 when it comes to browsing files via MTP.

**Comment by CarstenWpt** [comment] 2022-02-03 09:21
For me the same, MTP has become very slow :(

**Comment by 20Phoenix** [comment] 2022-02-03 09:22
For me the same, MTP is now very slow :(

**Comment by rashevskyv** [comment] 2022-02-03 15:19
Fixed on https://github.com/rashevskyv/dbi/releases/tag/358

Please trry

**Comment by BlackRabbit22** [comment] 2022-02-03 15:32
@rashevskyv Works fine now, issue seems to be fixed.
Thank you.

**Comment by rashevskyv** [comment] 2022-02-03 15:34
Nice! Thank you!

**Closed** 2022-02-03 15:35 UTC

**Comment by rashevskyv** [comment] 2022-02-03 16:11
I reopened accidentally.

**Comment by Lather0519** [comment] 2022-02-04 10:25
Oops😋
