### ISSUE TITLE
MTP transfer locks up in Windows once single NSZ is complete, Installation is successful on Switch

### ISSUE THREAD

**Issue by Kupie** [rashevskyv/dbi#91] opened 2022-02-15 05:33 UTC
Hello,

I used to be able to copy multiple NSZ files over via DBI's MTP responder for MicroSD install, however it locks up for a very long time after a single install is complete. This makes installing multiple NSZ files a pain, however I am able cancel MTP responder in DBI and relaunch it and then resume installing just fine. 

For example, a 100MB NSZ installs very quickly, but MTP responder locked up for a solid minute after the install was complete. With games in larger sizes (2-5GB) I have waited 3 minutes before just exiting MTP/restarting it and resuming.

This happens on two different switches, with two different PCs both running Windows 10. I'm not sure when exactly, but a couple months ago DBI did not have this issue.

**Comment by duckbill007** [comment] 2022-02-15 06:29
First - what version was ok?
Second - switch is a slave device in mtp, so if install success then all data was sent and issue on PC side. 
Third - bugs not reproducible on Linux won't be fixed because I do not have windows.

**Comment by HalfScoper** [comment] 2022-02-28 00:11
I experience similar issues, nevertheless my PC idles for like 30 seconds after installation is done and then either I can drag another file to install, or  it installs the next of those I copied at once (but this also sometimes fails and it "forgets" to install the rest).

**Closed** 2022-08-22 09:17 UTC
